#!/bin/bash
port=$1
db_conn="mysql -h 127.0.0.1 -uroot -proot@123 -P $port"
$db_conn -ss -e "select concat(\"kill \",trx_mysql_thread_id,\";\") as kill_id from information_schema.INNODB_TRX where trx_lock_structs=0 and trx_weight=0 and trx_rows_locked=0 and trx_rows_modified=0 and trx_state='RUNNING';"|$db_conn

$db_conn -ss -e "select concat(\"kill \",b.ID,\";\") as kill_id from information_schema.INNODB_TRX a,information_schema.PROCESSLIST b where a.trx_mysql_thread_id=b.ID and a.trx_state='RUNNING' and b.TIME >=30;"|$db_conn
